Przuchodnia_Medyczna_Inz/Controllers/PlacowkaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Przuchodnia_Medyczna_Inz.Models;
using Przuchodnia_Medyczna_Inz.DAL;

namespace Przuchodnia_Medyczna_Inz.Controllers
{
    [Authorize(Roles = "Administrator, Recepcja, Lekarz")]
    public class PlacowkaController : Controller
    {
        private PrzychodniaContext db = new PrzychodniaContext();

        // GET: /Placowka/
        public ActionResult Index()
        {
            var placowkamedyczna = db.PlacowkaMedyczna.Include(p => p.Adres);
            return View(placowkamedyczna.ToList());
        }

        [HttpPost]
        public ActionResult Create(string nazwa, string kom, string tel, string otwarte, string ulica, int budynek, string kod, string miejscowosc )
        {
            if (ModelState.IsValid)
            {
                var placowka = new PlacowkaMedyczna()
                {
                    Nazwa = nazwa,
                    Komorka = kom,
                    Telefon  = tel,
                    GodzinyOtwarcia = otwarte,
                    Adres = new Adres()
                        {
                            Ulica = ulica,
                            NrBudynku = budynek,
                            KodPocztowy = kod,
                            Miejscowosc = miejscowosc
                        }
                };
                db.PlacowkaMedyczna.Add(placowka);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: /Placowka/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlacowkaMedyczna placowkamedyczna = db.PlacowkaMedyczna.Find(id);
            if (placowkamedyczna == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Edit", placowkamedyczna);
        }

        // POST: /Placowka/Edit/5
        [HttpPost]
        public ActionResult Edit(PlacowkaMedyczna placowka)
        {
            if (ModelState.IsValid)
            {
                db.Entry(placowka).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            TempData["error"] = "Wystapił nie oczekiwany błąd. Edycja nie powiodła sie.";
            return RedirectToAction("Index");
        }

        // GET: /Placowka/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlacowkaMedyczna placowkamedyczna = db.PlacowkaMedyczna.Find(id);
            if (placowkamedyczna == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Delete",placowkamedyczna);
        }

        // POST: /Placowka/Delete/5
        [HttpPost, ActionName("Delete")]       
        public ActionResult DeleteConfirmed(int id)
        {
            PlacowkaMedyczna placowkamedyczna = db.PlacowkaMedyczna.Find(id);
            db.PlacowkaMedyczna.Remove(placowkamedyczna);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Przuchodnia_Medyczna_Inz/Controllers/StanowiskoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Przuchodnia_Medyczna_Inz.Models;
using Przuchodnia_Medyczna_Inz.DAL;

namespace Przuchodnia_Medyczna_Inz.Controllers
{
     [Authorize(Roles = "Administrator, Recepcja, Lekarz")]
    public class StanowiskoController : Controller
    {
        private PrzychodniaContext db = new PrzychodniaContext();

        // GET: /Stanowisko/
        public ActionResult Index()
        {
            return View(db.Stanowisko.ToList());
        }

        // GET: /Stanowisko/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stanowisko stanowisko = db.Stanowisko.Find(id);
            if (stanowisko == null)
            {
                return HttpNotFound();
            }

            if (!Request.IsAjaxRequest())
            {
                return View(stanowisko);
            }
            else
            {
                return PartialView("_Details", stanowisko);

            }
        }

        // GET: /Stanowisko/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Stanowisko/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(string nazwa, string obowiazki)
        {
            if (ModelState.IsValid)
            {
                var stanowisko = new Stanowisko();
                stanowisko.Nazwa = nazwa;
                stanowisko.Obowiazki = obowiazki;

                db.Stanowisko.Add(stanowisko);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: /Stanowisko/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stanowisko stanowisko = db.Stanowisko.Find(id);
            if (stanowisko == null)
            {
                return HttpNotFound();
            }
            return View(stanowisko);
        }

        // POST: /Stanowisko/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="StanowiskoID,Nazwa,Obowiazki")] Stanowisko stanowisko)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stanowisko).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(stanowisko);
        }

        // GET: /Stanowisko/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stanowisko stanowisko = db.Stanowisko.Find(id);
            if (stanowisko == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Delete", stanowisko);
        }

        // POST: /Stanowisko/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Stanowisko stanowisko = db.Stanowisko.Find(id);
            db.Stanowisko.Remove(stanowisko);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Przuchodnia_Medyczna_Inz/Controllers/WizytaController.cs
using Przuchodnia_Medyczna_Inz.DAL;
using Przuchodnia_Medyczna_Inz.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity.Validation;
using System.Diagnostics;
using PagedList;
using Przuchodnia_Medyczna_Inz.Helpers;

namespace Przuchodnia_Medyczna_Inz.Controllers
{
    public class WizytaController : Controller
    {
        private PrzychodniaContext db = new PrzychodniaContext();

        // Post: /Wizyta/
       [Authorize]
        public ActionResult Index(string startDate, string status, string endDate, string lekarz, ActionMessage akcja = ActionMessage.Empty, string info = null, string data = null)
        {
            List<Wizyta> wizyty;
            var userId = User.Identity.GetUserId();

            if(User.IsInRole("Pacjent") && !String.IsNullOrEmpty(status)){
                var stat = (Status)Enum.Parse(typeof(Status), status);
                wizyty = db.Wizyta.Where(x => x.Pacjent.OsobaID.Equals(userId) && x.Status == stat).ToList();
            }
            else if (User.IsInRole("Pacjent"))
            {
                wizyty = db.Wizyta.Where(x => x.Pacjent.OsobaID.Equals(userId) && x.Status == Status.Zaplanowana).ToList();
            }
            else
            {
                wizyty = db.Wizyta.Where(x =>x.PacjentID != null).ToList();
            }
            var liczbaWizyt = wizyty.Count();
            DateTime start;
            DateTime end;

            if (!String.IsNullOrEmpty(startDate))
            {
                start = DateTime.ParseExact(startDate, "dd/MM/yyyy", CultureInfo.InvariantCulture); 
                wizyty = wizyty.Where(x => x.Data >= start).ToList();
            }
            if (!String.IsNullOrEmpty(endDate))
            {
                end = DateTime.ParseExact(endDate, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                wizyty = wizyty.Where(x => x.Data <= end).ToList();
            }            
            TempData["startDate"] = startDate;
            TempData["endDate"] = endDate;
            ViewBag.Wizyty = liczbaWizyt;

            if (akcja != ActionMessage.Empty)
            {
                ViewBag.data = data;
                ViewBag.info = info;
                ViewBag.Akcja = akcja;
            }

            return View(wizyty.OrderByDescending(x => x.Data));
        }

        //POST
        [HttpPost]
        [Authorize(Roles = "Lekarz")]
        public ActionResult CreateTermin(DateTime data, DateTime godzina, string uwagi, string Id)
        {
                Wizyta wizyta = new Wizyta();

                try
                {
                    Wizyta czyWizytaJuzIstnieje = db.Wizyta.Where(x => x.Data == data
                                                               && x.Godzina.Hour == godzina.Hour
                                                               && x.Godzina.Minute == x.Godzina.Minute
                                                               && x.PracownikID.Equals(Id)).First();

                    if (czyWizytaJuzIstnieje == null)
                    {
                        wizyta.Status = Status.Wolna;
                        wizyta.PracownikID = Id;
                        wizyta.Data = data;
                        wizyta.Godzina = godzina;
                        wizyta.Uwagi = uwagi;
                        db.Wizyta.Add(wizyta);

                        db.SaveChanges();
                        return RedirectToAction("Terminy", "Pracownik", new { id = Id });
                    }
                    else
                    {
                        return RedirectToAction("Terminy", "Pracownik", new { id = Id, akcja = "Podany termin już istnieje. Podaj inny termin." });
                    }
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Terminy", "Pracownik", new { akcja = PracownikActionMessage.Error, info = ex.ToString() });
                }
        }

        [HttpPost]
        [Authorize(Roles = "Lekarz")]
        public ActionResult Diagnoza(string diagnoza, string Id)
        {
            var wizytaId = Int32.Parse(Id);
            
                Wizyta wizyta = db.Wizyta.Where(x => x.WizytaID == wizytaId).First();

                wizyta.Status = Status.Odbyta;
                wizyta.Diagnoza = diagnoza;
                db.SaveChanges();
                return RedirectToAction("MojeWizyty", "Pracownik");
        }
        public ActionResult VisitList(string id, string startDate, string endDate)
        {
            var start = DateTime.ParseExact(startDate, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            var end = DateTime.ParseExact(endDate, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            var wizyty = db.Wizyta.Where(x => x.Data >= start && x.Data <= end && x.PracownikID.Equals(id) && x.Status == Status.Wolna).ToList();

            return PartialView("_VisitList", wizyty.OrderByDescending(x => x.Data).ToList());
        }
        // GET: /Wizyta/Create
        public ActionResult Create()
        {
            return View();
        }

         [Authorize(Roles = "Recepcja, Pacjent")]
        public ActionResult Rezerwacja(int id)
        {
            var userId = User.Identity.GetUserId();
            var pacjent = db.Pacjent.Where(x => x.OsobaID.Equals(userId));

            Wizyta wizyta = db.Wizyta.Find(id);
            try
            {
                if (wizyta != null)
                {
                    wizyta.PacjentID = userId;
                    wizyta.Status = Status.Zaplanowana;
                    db.SaveChanges();

                    return RedirectToAction("Index", new { akcja = ActionMessage.Created, info = wizyta.Pracownik.ImieNazwisko, data = wizyta.Data });
                }
                else
                {
                    return HttpNotFound();
                }
            }
            catch(Exception ex)
            {
                return RedirectToAction("Index", new { akcja = ActionMessage.Error });
                ex.ToString();
            }
        }

        public ActionResult GetLekarz(string lekarz)
        {
            List<SelectListItem> listaLekarzy = new List<SelectListItem>();
            if (!string.IsNullOrEmpty(lekarz))
            {
                var lekarze = db.Pracownik.Where(x => x.Stanowiska.Nazwa.Equals("Lekarz") && x.Specjalizacja.Nazwa.Equals(lekarz)).ToList();
                lekarze.ForEach(x => 
                {
                    listaLekarzy.Add(new SelectListItem { Text = x.ImieNazwisko, Value = x.OsobaID });
                });
            }
            return Json(listaLekarzy, JsonRequestBehavior.AllowGet);
        }
        
        // GET: /Wizyta/Edit/5
         [Authorize(Roles = "Lekarz")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wizyta wizyta = db.Wizyta.Find(id);

            if (wizyta == null)
            {
                return HttpNotFound();
            }
            return PartialView("_NewDiagnoza", wizyta);
        }

        // POST: /Wizyta/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit(Wizyta wizyta)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(wizyta).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Terminy", "Pracownik", new { akcja = ActionMessage.Edited, info = wizyta.Pracownik.ImieNazwisko });
            }
            catch(Exception ex)
            {
                return RedirectToAction("Terminy","Pracownik", new { akcja = ActionMessage.Error });
                ex.ToString();
            }
        }

        // GET: /Wizyta/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wizyta wizyta = db.Wizyta.Find(id);

            if (wizyta == null)
            {
                return HttpNotFound();
            }

            return PartialView("_Delete", wizyta);
        }

        // POST: /Wizyta/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id, string pacjentId)
        {
            try
            {
                
                Wizyta wizyta = db.Wizyta.Find(id);

                if (wizyta.Status == Status.Odbyta || wizyta.Data < DateTime.Today)
                {
                    wizyta.Status = Status.Archiwum;
                    db.SaveChanges();

                    if (String.IsNullOrEmpty(pacjentId))
                    {
                        return RedirectToAction("Index", new { akcja = "Wizyta została usunięta z twojej listy"});
                    }

                }
                else
                {
                    wizyta.PacjentID = null;
                    wizyta.Status = Status.Wolna;
                    db.SaveChanges();

                    if (String.IsNullOrEmpty(pacjentId))
                    {
                        return RedirectToAction("Index", new { akcja = ActionMessage.Deleted, info = wizyta.Pracownik.ImieNazwisko, data = wizyta.Data });
                    }
                }
                return RedirectToAction("Wizyty", "Pacjent", new { id = pacjentId});
            }
            catch (Exception ex)
            {

Przuchodnia_Medyczna_Inz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Przychodnia Medyczna</title>
    <meta name="keywords" content="Play-Offs Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() {setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--fonts-->
    <link href='http://fonts.googleapis.com/css?family=Monda:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,300,100,700' rel='stylesheet' type='text/css'>
    <!--fonts-->
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/navi")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/infoCzynnosc.js")
    <!-- Include Date Range Picker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
</head>
<body>
    <div class="header_nav" id="home">
        <nav class="navbar navbar-default chn-gd">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("AnesMed", "Index", "Home", null, new { @class = "navbar-brand logo-st" })
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right" style="position:relative">
                        @if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("Pacjent")|| HttpContext.Current.User.IsInRole("Administrator")) { 
                            @*<li>
                                <a href="@Url.Action("Home", "PacjentHome", new{ @class="scroll"})">
                                    <span class="glyphicon glyphicon-home icn_pos hm" aria-hidden="true"></span><br>
                                    Home
                                </a>
                            </li>*@
                            <li>
                                <a href="@Url.Action("Index", "Wizyta", new{ @class="scroll"})">
                                    <span class="glyphicon glyphicon-calendar icn_pos hm" aria-hidden="true"></span><br>
                                    Wizyty
                                </a>
                            </li>
                           
                        }
                        @if (Request.IsAuthenticated && !(HttpContext.Current.User.IsInRole("Pacjent")) && !(HttpContext.Current.User.IsInRole("Lekarz")))
                        {
                            <li>
                                <a href="@Url.Action("Index", "Pacjent", new { @class = "scroll" })">
                                    <span class="glyphicon glyphicon-user icn_pos" aria-hidden="true"></span><br>
                                    Pacjenci
                                </a>
                            </li>                            
                        }
                        @if (!Request.IsAuthenticated) 
                        { 
                        <!---->
                        <li>
                            <a href="#features" class="scroll">
                                <span class="glyphicon glyphicon-cog icn_pos" aria-hidden="true"></span><br>
                                Usługi
                            </a>
                        </li>
                        <!---->
                        <li>
                            <a href="#doc" class="scroll">
                                <span class="glyphicon glyphicon-briefcase icn_pos" aria-hidden="true"></span><br>
                                Lekarze
                            </a>
                        </li>
                        }
                        @if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("Administrator"))
                        {
                            <li>
                                <div class="dropdown" style="margin-top: 2px">
                                    <a href="#doc" class="dropbtn">
                                        <span class="glyphicon glyphicon-user icn_pos" aria-hidden="true"></span><br>
                                        Pracownicy
                                    </a>
                                    <div class="dropdown-content">
                                        @Html.ActionLink("Lekarze", "Index", "Pracownik" ,new { stanowisko = "Lekarz"}, null)
                                        @Html.ActionLink("Recepcja", "Index", "Pracownik", new { stanowisko = "Recepcja" }, null)
                                        @Html.ActionLink("Konserwacja", "Index", "Pracownik", new { stanowisko = "Konserwator" }, null)
                                        @Html.ActionLink("Serwis Sprzątający", "Index", "Pracownik", new { stanowisko = "Serwis_Sprzatajacy" }, null)
                                        @Html.ActionLink("Pielęgniarki", "Index", "Pracownik", new { stanowisko = "Pielęgniarka" }, null)
                                        @Html.ActionLink("Administratorzy", "Index", "Pracownik",new { stanowisko = "Administrator" }, null)
                                    </div>
                                </div>
                            </li> 
                       
                        <li>
                            <div class="dropdown" style="margin-top: 2px">
                                <a href="#doc" class="dropbtn">
                                    <span class="glyphicon glyphicon-paperclip icn_pos" aria-hidden="true"></span><br>
                                    Zarzadzanie
                                </a>
                                <div class="dropdown-content">
                                    @Html.ActionLink("Specjalizacje", "Index", "Specjalizacja")
                                    @Html.ActionLink("Stanowiska", "Index", "Stanowisko")
                                    @Html.ActionLink("Placówki", "Index", "Placowka")
                                </div>
                            </div>
                        </li>
                                                        
                        }
                       @if (Request.IsAuthenticated && (HttpContext.Current.User.IsInRole("Lekarz") || HttpContext.Current.User.IsInRole("Recepcja")))
                        {
                        <li>
                            <div class="dropdown" style="margin-top: 2px">
                                <a href="#doc" class="dropbtn">
                                    <span class="glyphicon glyphicon-paperclip icn_pos" aria-hidden="true"></span><br>
                                    Zarzadzanie
                                </a>
                                <div class="dropdown-content">
                                    @Html.ActionLink("Specjalizacje", "Index", "Specjalizacja")
                                    @Html.ActionLink("Stanowiska", "Index", "Stanowisko")
                                    @Html.ActionLink("Placówki", "Index", "Placowka")
                                </div>
                            </div>
                        </li>
                        }       
                        @if (Request.IsAuthenticated && (HttpContext.Current.User.IsInRole("Lekarz")))
                        {
                             <li>
                                <a href="@Url.Action("MojeWizyty", "Pracownik", new{ @class="scroll"})">
                                    <span class="glyphicon glyphicon-calendar icn_pos hm" aria-hidden="true"></span><br>
                                    Moje Wizyty
                                </a>
                            </li>
                        }
                        @if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("Pacjent")|| !(Request.IsAuthenticated))
                        {
                        <li>
                            <a href="#contact" class="scroll">
                                <span class="glyphicon glyphicon-envelope icn_pos" aria-hidden="true"></span><br>
                                Kontakt
                            </a>
                        </li>
                        }
                        @Html.Partial("_LoginPartial")                      
                       
                    </ul>
                </div><!-- /.navbar-collapse -->
                <div class="clearfix"></div>
            </div><!-- /.container-fluid -->
        </nav>
    </div>
    <div class="container body-content">
        @RenderBody()
        <footer>
            <div class="footer" style="margin-top: 100px;">
                <div class="container-fluid">
                    <div class="footer-text">
                        <h3><a href="index.html">Przychodnia AnesMed</a></h3>
                        <p>Projekt inżynierski - Julia Majewska</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
   <!--script-->
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(".scroll").click(function (event) {
            event.preventDefault();
            $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 900);
        });
    });
</script>
<!--script-->

Przuchodnia_Medyczna_Inz/Views/Shared/_NewDiagnoza.cshtml
@model Przuchodnia_Medyczna_Inz.Models.Wizyta

@Html.ValidationSummary(true)
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-body">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title title" style="font-size:25px;">Diagnoza </h4>
            </div>
            @using(Html.BeginForm("Edit", "Wizyta", FormMethod.Post))
            {
            <div class="modal-body">
                @Html.HiddenFor(model => model.Pacjent.OsobaID)
                @Html.HiddenFor(model => model.WizytaID)
                <div class="form-group">
                    <label class="control-label col-md-3">Pacjent</label>
                    <div class="col-md-5">
                        @Html.TextBoxFor(model => model.Pacjent.ImieNazwisko, new { @class = "form-control", @readOnly = "true" })
                        @Html.ValidationMessageFor(model => model.Pacjent.ImieNazwisko)
                    </div>
                </div>
                <br /><br />
                <div class="form-group">
                    @Html.LabelFor(model => model.Pacjent.Pesel, new { @class = "control-label col-md-3" })
                    <div class="col-md-5">
                        @Html.TextBoxFor(model => model.Pacjent.Pesel, new { @class = "form-control", @readOnly="true" })
                        @Html.ValidationMessageFor(model => model.Pacjent.Pesel)
                    </div>
                </div>
                <br /><br />
                <div class="form-group">
                    @Html.LabelFor(model => model.Diagnoza, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Diagnoza, new { @class = "form-control", @cols = 50, @rows = 20 })
                        @Html.ValidationMessageFor(model => model.Diagnoza)
                    </div>
                </div>
            </div>
            <br />
            <div class="modal-footer" style="margin-top: 380px;">
                <button class="btn btn-success" onclick="DiagnozaAdd()">Zapisz</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Anuluj</button>
            </div>
            }
        </div>
    </div>
</div>