Przuchodnia_Medyczna_Inz/Models/Pacjent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

namespace Przuchodnia_Medyczna_Inz.Models
{
    public class Pacjent : Osoba
    {
        public Pacjent()
        {
            this.Wizyty = new HashSet<Wizyta>();
            this.ChorobyPacjenta = new HashSet<PacjentChorobaPrzewlekla>();
        }
        [Required]
        [RegularExpression(@"^((\d{3}[-]\d{3}[-]\d{2}[-]\d{2})|(\d{3}[-]\d{2}[-]\d{2}[-]\d{3}))$", ErrorMessage = "Niepoprawny format numeru NIP!")]
        public string NIP { get; set; }
        public string Informacje { get; set; }
        public virtual ICollection<Wizyta> Wizyty { get; set; }
        public virtual ICollection<PacjentChorobaPrzewlekla> ChorobyPacjenta { get; set; }
    }
}

Przuchodnia_Medyczna_Inz/Controllers/AdresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Przuchodnia_Medyczna_Inz.DAL;
using Przuchodnia_Medyczna_Inz.Models;

namespace MAS_Przychodnia_Medyczna_ProjKoncowy.Controllers
{
    [Authorize]
    public class AdresController : Controller
    {
        private PrzychodniaContext db = new PrzychodniaContext();

        // GET: /Adres/
        public ActionResult Index()
        {
            var adres = db.Adres.Include(a => a.PlacowkaMedyczna);
            return View(adres.ToList());
        }

        // GET: /Adres/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adres adres = db.Adres.Find(id);
            if (adres == null)
            {
                return HttpNotFound();
            }
            return View(adres);
        }

        // GET: /Adres/Create
        public ActionResult Create()
        {
            ViewBag.PlacowkaID = new SelectList(db.PlacowkaMedyczna, "PlacowkaMedycznaID", "Nazwa");
            return View();
        }

        // POST: /Adres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AdresID,PlacowkaID,Miejscowosc,Ulica,NrBudynku,NrMieszkania,KodPocztowy")] Adres adres)
        {
            if (ModelState.IsValid)
            {
                db.Adres.Add(adres);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.PlacowkaID = new SelectList(db.PlacowkaMedyczna, "PlacowkaMedycznaID", "Nazwa", adres.PlacowkaID);
            return View(adres);
        }

        // GET: /Adres/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adres adres = db.Adres.Find(id);
            var os = db.Osoba.Where(x => x.Adres.AdresID == id).FirstOrDefault();
            ViewBag.OsobaID = os.OsobaID;
            if (adres == null)
            {
                return HttpNotFound();
            }
            return View(adres);
        }

        // POST: /Adres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AdresID,PlacowkaID,Miejscowosc,Ulica,NrBudynku,NrMieszkania,KodPocztowy")] Adres adres)
        {
            if (ModelState.IsValid)
            {
                db.Entry(adres).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Message"] = "Edycja 'danych adresowych:'" + adres.FullAdres + " zakończona powodzeniem.";
                return RedirectToAction("Index", "Pacjent", null);
            }
            return View(adres);
        }

        // GET: /Adres/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adres adres = db.Adres.Find(id);
            if (adres == null)
            {
                return HttpNotFound();
            }
            return View(adres);
        }

        // POST: /Adres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Adres adres = db.Adres.Find(id);
            db.Adres.Remove(adres);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Przuchodnia_Medyczna_Inz/Controllers/PacjentController.cs
using PagedList;
using Przuchodnia_Medyczna_Inz.DAL;
using Przuchodnia_Medyczna_Inz.Helpers;
using Przuchodnia_Medyczna_Inz.Models;
using Przuchodnia_Medyczna_Inz.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Przuchodnia_Medyczna_Inz.Controllers
{
    public class PacjentController : Controller
    {
        private PrzychodniaContext db = new PrzychodniaContext();
        // GET: /Pacjent/
        [Authorize(Roles="Administrator, Recepcja")]
        public ActionResult Index(string imieNazwisko, string pesel, int page = 1, PacjentActionMessage akcja = PacjentActionMessage.Empty, string info = null)
        {
                    var pacjenci = new AdresyOsobVM();

                    pacjenci.Pacjenci = (from p in db.Pacjent select p).OrderBy(p => p.Nazwisko).ToList();
                    pacjenci.Adresy = from a in db.Adres select a;

                    if (!String.IsNullOrEmpty(imieNazwisko))
                    {
                        pacjenci.Pacjenci = pacjenci.Pacjenci.Where(s => s.ImieNazwisko.Contains(imieNazwisko)).ToList();
                    }
                    if (!String.IsNullOrEmpty(pesel))
                    {
                        pacjenci.Pacjenci = pacjenci.Pacjenci.Where(p => p.Pesel.ToString().Contains(pesel)).ToList();
                    }

                    if (akcja != PacjentActionMessage.Empty)
                    {
                        ViewBag.info = info;
                        ViewBag.Akcja = akcja;
                    }

                    int pageSize = 10;
                    int pageNumber = 1;

                    PagedList<Pacjent> model = new PagedList<Pacjent>(pacjenci.Pacjenci.OrderBy(x => x.Nazwisko), page, pageSize);

                    return View(model);

        }
        // GET: /Pacjent/Details/5
         [Authorize(Roles = "Administrator, Recepcja")]
        public ActionResult Wizyty(string id)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var pacjent = db.Pacjent.Find(id);

            if (pacjent == null)
            {
                return HttpNotFound();
            }
            return View(pacjent);
        }
        // GET: /Pacjent/Create
        [Authorize(Roles = "Administrator, Recepcja")]
        public ActionResult Create()
        {
            ViewBag.AdresID = new SelectList(db.Adres, "AdresID", "Miejscowosc");
            return View();
        }

        // POST: /Pacjent/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Recepcja")]
        public ActionResult Create(AdresyOsobVM model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Adres adres = new Adres();
                    Pacjent pacjent = new Pacjent();

                    pacjent.Imie = model.Pacjent.Imie;
                    pacjent.Nazwisko = model.Pacjent.Nazwisko;
                    pacjent.Pesel = model.Pacjent.Pesel;
                    pacjent.NIP = model.Pacjent.NIP;
                    pacjent.Telefon = model.Pacjent.Telefon;

                    adres.Ulica = model.Adres.Ulica;
                    adres.NrBudynku = model.Adres.NrBudynku;
                    adres.NrMieszkania = model.Adres.NrMieszkania;
                    adres.KodPocztowy = model.Adres.KodPocztowy;
                    adres.Miejscowosc = model.Adres.Miejscowosc;

                    pacjent.Adres = adres;

                    db.Osoba.Add(pacjent);
                    db.SaveChanges();
                    return RedirectToAction("Index", new { akcja = PacjentActionMessage.Create, info = pacjent.ImieNazwisko });
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Index", new { akcja = PacjentActionMessage.Error, info = ex.ToString() });
                }
            }
            return View(model);
        }
        // GET: /Pacjent/Edit/5
          [Authorize(Roles = "Administrator, Recepcja")]
        public ActionResult Edit(string id)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Pacjent pacjent = db.Pacjent.Find(id);
            ViewBag.AdresId = from a in db.Osoba where a.Adres.AdresID.Equals(id) select a;

            if (pacjent == null)
            {
                return HttpNotFound();
            }

            return View(pacjent);
        }

        // POST: /Pacjent/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Recepcja")]
        public ActionResult Edit([Bind(Include = "OsobaID,AdresID,Imie,Nazwisko,Telefon,Pesel,NIP")] Pacjent pacjent)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(pacjent).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index", new { akcja = PacjentActionMessage.Edit, info = pacjent.ImieNazwisko });
                }
                catch(Exception ex)
                {
                    return RedirectToAction("Index", new { akcja = PacjentActionMessage.Error, info = ex.ToString() });
                }
            }

            return View(pacjent);
        }

        // GET: /Pacjent/Delete/5
          [Authorize(Roles = "Administrator, Recepcja")]
        public ActionResult Delete(string id)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pacjent pacjent = db.Pacjent.Find(id);
            if (pacjent == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Delete",pacjent);
        }

        // POST: /Pacjent/Delete/5
        [HttpPost, ActionName("_Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Recepcja")]
        public ActionResult DeleteConfirmed(string id)
        {
            Pacjent pacjent = db.Pacjent.Find(id);
            db.Osoba.Remove(pacjent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Przuchodnia_Medyczna_Inz/Views/Pacjent/Create.cshtml
@model Przuchodnia_Medyczna_Inz.Models.RegisterViewModel

@{
    ViewBag.Title = "Create";
}
<div class="col-md-8 col-md-offset-4">
    <br />
    <h2 class="title">Dodaj Pacjenta</h2>
    <br />
</div>

@using (Html.BeginForm("Register", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="col-md-11 col-md-offset-1">
    <div class="form-group">
        @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
        </diV>
    
    <h3 class="sub-title">Dane Personalne:</h3>
    <hr />
     <div class="col-md-11 col-md-offset-1">
    <div class="form-group">
        @Html.LabelFor(model => model.AdresyOsob.Pacjent.Imie, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.AdresyOsob.Pacjent.Imie, new { @class = "form-control", @placeholder = "Imie" })
            @Html.ValidationMessageFor(model => model.AdresyOsob.Pacjent.Imie)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AdresyOsob.Pacjent.Nazwisko, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.AdresyOsob.Pacjent.Nazwisko, new { @class = "form-control", @placeholder = "Nazwisko" })
            @Html.ValidationMessageFor(model => model.AdresyOsob.Pacjent.Nazwisko)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AdresyOsob.Pacjent.Telefon, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.AdresyOsob.Pacjent.Telefon, new { @class = "form-control", @placeholder = "Numer telefonu" })
            @Html.ValidationMessageFor(model => model.AdresyOsob.Pacjent.Telefon)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AdresyOsob.Pacjent.Pesel, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.AdresyOsob.Pacjent.Pesel, new { @class = "form-control", @placeholder = "Numer Pesel" })
            @Html.ValidationMessageFor(model => model.AdresyOsob.Pacjent.Pesel)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AdresyOsob.Pacjent.NIP, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.AdresyOsob.Pacjent.NIP, new { @class = "form-control", @placeholder = "np. 123-132-32-12" })
            @Html.ValidationMessageFor(model => model.AdresyOsob.Pacjent.NIP)
        </div>
    </div>
        </div>
    <br />
    <h3 class="sub-title">Adres:</h3>
    <hr />
    <div class="form-group">
        @Html.LabelFor(model => model.AdresyOsob.Adres.Ulica, "Ulica", new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            @Html.TextBoxFor(m => m.AdresyOsob.Adres.Ulica, new { @class = "form-control", @placeholder = "Ulica" })
            @Html.ValidationMessageFor(model => model.AdresyOsob.Adres.Ulica)
        </div>

        @Html.LabelFor(model => model.AdresyOsob.Adres.NrBudynku, "Nr Bud.", new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.TextBoxFor(m => m.AdresyOsob.Adres.NrBudynku, new { @class = "form-control", @placeholder = "nr budynku" })
            @Html.ValidationMessageFor(model => model.AdresyOsob.Adres.NrBudynku)
        </div>

        @Html.LabelFor(model => model.AdresyOsob.Adres.NrMieszkania, "Nr Lokalu", new { @class = "control-label col-md-1" })
        <div class="col-md-2">
            @Html.TextBoxFor(m => m.AdresyOsob.Adres.NrMieszkania, new { @class = "form-control", @placeholder = "nr lokalu" })
            @Html.ValidationMessageFor(model => model.AdresyOsob.Adres.NrBudynku)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AdresyOsob.Adres.KodPocztowy, "Kod Pocztowy", new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            @Html.TextBoxFor(m => m.AdresyOsob.Adres.KodPocztowy, new { @class = "form-control", @placeholder = "Kod Pocztowy" })
            @Html.ValidationMessageFor(model => model.AdresyOsob.Adres.KodPocztowy)
        </div>
        @Html.LabelFor(model => model.AdresyOsob.Adres.Miejscowosc, "Miejscowość", new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            @Html.TextBoxFor(m => m.AdresyOsob.Adres.Miejscowosc, new { @class = "form-control", @placeholder = "Miejscowość" })
            @Html.ValidationMessageFor(model => model.AdresyOsob.Adres.Miejscowosc)
        </div>
    </div>
    <br /> <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-7">
            <input type="submit" class="btn btn-success col-md-10" value="Zapisz" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Przuchodnia_Medyczna_Inz/Views/Pacjent/Edit.cshtml
@model Przuchodnia_Medyczna_Inz.Models.Pacjent

@{
    ViewBag.Title = "Edycja danych";
}
<div class="col-md-8 col-md-offset-4">
    <br />
    <h2 class="title">Edycja danych pacjenta</h2>
    <br />
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.OsobaID)

        <div class="container">
            <hr />
            <div class="row">
                <div class="col-md-6">
                    <h4 class="sub-title">Dane osobowe:</h4>
                </div>
                <div class="col-md-6">
                    <h4 class="sub-title">Dane adresowe:</h4>
                    <button class="btn btn-info btn-sm" onclick="location.href='@Url.Action("Edit", "Adres", new { id = @Model.Adres.AdresID}, null)'; return false">
                        Edytuj                   
                    </button>                     
                </div>
                <br/>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Imie, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Imie, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Imie)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Nazwisko, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Nazwisko, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Nazwisko)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Telefon, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Telefon, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Telefon)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Pesel, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Pesel, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Pesel)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.NIP, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.NIP, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.NIP)
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-6 col-md-6">
                            <input type="submit" value="Zapisz" class="btn btn-success" />
                        </div>
                    </div>
                </div>     
                <br/>
            </div>
        </div>
    </div>
}


<div class="col-md-12">
    <a href="@Url.Action("Index", "Pacjent")" title="Powrót">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true" style="font-size: 25px;"></span>
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Przuchodnia_Medyczna_Inz/Views/Pacjent/Index.cshtml
@model PagedList.IPagedList<Przuchodnia_Medyczna_Inz.Models.Pacjent>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Pacjenci";
}
<br />
@if (ViewBag.Akcja != null)
{
    if (ViewBag.Akcja == Przuchodnia_Medyczna_Inz.Helpers.PacjentActionMessage.Edit ||
        ViewBag.Akcja == Przuchodnia_Medyczna_Inz.Helpers.PacjentActionMessage.Create)
    {
        <div class="alert alert-success">

            <h4>@Przuchodnia_Medyczna_Inz.Helpers.FullDescription.GetDescription(@ViewBag.Akcja)<b>@ViewBag.info</b></h4>
        </div>
    }

    if (ViewBag.Akcja == Przuchodnia_Medyczna_Inz.Helpers.PacjentActionMessage.Error)
    {
        <div class="alert alert-danger">
          
            <h4>@Przuchodnia_Medyczna_Inz.Helpers.FullDescription.GetDescription(@ViewBag.Akcja) <b>@ViewBag.info</b></h4>
           
        </div>
    }
}
@if(Request.IsAuthenticated && !(User.IsInRole("Lekarz"))){
<div class="container">
    <div class="row" style="margin-right: 20px;">
        <div class="title col-md-6 col-md-offset-4"> Lista pacjentów</div>
        <div class="col-md-2">
            <a href="@Url.Action("Create", "Pacjent")" class="btn btn-success">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                Dodaj Pacjenta
            </a>
        </div>
    </div>
</div>
}
<br />
@using (Html.BeginForm()) { 
<div class="container" style="background-color: #309BBE; color: white; border-radius: 15px; height: 120px;">
    <div class="row">
        <div class="col-md-3">
            <br />
            <h4>Imie Nazwisko: @Html.TextBox("imieNazwisko", null, new { @class = "form-control", @placeholder = "Imie Nazwisko" })</h4>           
        </div>
        <div class="col-md-3">
            <br />
            <h4>Pesel: @Html.TextBox("Pesel", null, new { @class = "form-control", @placeholder="nr. Pesel" })</h4>
        </div>
        <div class="col-md-offset-3">
            <button style="margin-top: 4.4%;" class=" btn btn-default" type="submit">
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                Szukaj
            </button>        
        </div>
    </div>
</div>
}

<br />
<table class="table">
    <tr class="head-table">
        <th>Imie Nazwisko</th>
        <th>Pesel</th>
        <th>Telefon</th>
        <th>NIP</th>
        <th>Adres</th>
        <th></th>
    </tr> 
   @foreach(var item in Model)
   {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ImieNazwisko)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pesel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NIP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Adres.FullAdres)

        </td>
        <td>
            <a class="btn btn-xs btn-default buttons-xs" href="@Url.Action("Wizyty", new { id = item.OsobaID })" title="Wizyty pacjenta">
                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> Wizyty
            </a>  
            @if(Request.IsAuthenticated && !(User.IsInRole("Lekarz"))){  
            <a class="btn btn-xs btn-info buttons-xs" href="@Url.Action("Edit", new { id = item.OsobaID })" title="Edycja danych">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edutuj
            </a>
            <a href="@Url.Action("Delete", new { id = item.OsobaID })" data-toggle="modal" data-target="#pacjent-delete" title="Usuń">
                <span class="glyphicon glyphicon-trash icon" aria-hidden="true"></span>
            </a>
            }
        </td>
    </tr>
   }
</table>

<div id="pacjent-delete" class="modal fade hidden-print" tabindex="-1" role="dialog">
</div>

<div class="col-md-offset-5" style="margin-top: 10em; margin-bottom: -20px;">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index", new { stanowisko = @ViewBag.StanowiskoNazwa, page }))
</div>

<script>
    var emptyModalContent = function () {
        $('#pacjent-delete').removeData('bs.modal').find('.modal-content').empty();
    };
    $('#pacjent-delete').on('hidden.bs.modal', function () {
        emptyModalContent();
    });
</script>

Przuchodnia_Medyczna_Inz/Views/Pacjent/_Delete.cshtml
@model Przuchodnia_Medyczna_Inz.Models.Pacjent

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-body">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h3 class="title" style="font-size: 25px;">Usuń pacjenta</h3>
            </div>
            <div class="modal-body">
                <h4 class="sub-title">Czy napewno chcesz usunać pacjenta <b>@Html.DisplayFor(model => model.ImieNazwisko)</b>?</h4>
            </div>

            <div class="modal-footer">
                @using (Html.BeginForm())
                {
                    <input type="submit" value="Usuń" class="btn btn-danger" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Anuluj</button>
                }
            </div>
        </div>
    </div>
</div>